### ISSUE TITLE
peculiar handling of parentheses in predicates

### ISSUE THREAD

**Issue by RichMorin** [vic/spec#2]
The `conform/2` macro fails when the predicate is used without parentheses:

    iex(1)> use Spec
    Spec.Kernel
    iex(2)> conform(is_number(), 24)
    {:ok, 24}
    iex(3)> conform(is_number, 24)  
    ** (CompileError) iex:3: undefined function is_number/0
        expanding macro: Spec.conform/2
        iex:3: (file)

No error occurs when the predicate is used directly:

    iex(3)> 24 |> is_number
    true

**Comment by vic** [comment]
Yep, that is because of elixir syntax. If you see the error, not using parenthesis makes elixir think you refer to is_number/0 which does not exist.
